**Restaurantes**

url=https://datos.canarias.es/catalogos/general/dataset/establecimientos-de-restauracion-inscritos-en-el-registro-general-turistico-de-canarias

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\establecimientos-de-restauracion-inscritos-en-el-registro-general-turistico-de-canarias.csv",sep=";")

df_el_hierro = df[df["direccion_isla_nombre"].str.strip().str.lower() == "el hierro"]

df_el_hierro.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\el_hierro_ocio\dirty_dataset\restauracion_el_hierro_sucio.csv", index=False, sep=";")

print("✔ Archivo generado")
print("Total registros de El Hierro:", len(df_el_hierro))

✔ Archivo generado
Total registros de El Hierro: 98

In [4]:
import pandas as pd
import urllib.parse

df = pd.read_csv(
    r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\el_hierro_ocio\dirty_dataset\restauracion_el_hierro_sucio.csv",
    sep=";"
)

df = df.rename(columns={
    "direccion_municipio": "municipio",
    "establecimiento_nombre_comercial": "nombre",
    "establecimiento_grupo": "grupo"
})

df["municipio"] = df["municipio"].astype(str).str.strip()
df["nombre"] = df["nombre"].astype(str).str.strip()
df["grupo"] = df["grupo"].astype(str).str.strip()

df = df[df["municipio"] != "_U"]

df = df[df["municipio"].isin(["Frontera", "Valverde"])]

def maps_url(nombre, municipio):
    q = urllib.parse.quote(f"{nombre} {municipio} El Hierro")
    return f"https://www.google.com/maps/search/{q}"

rows = []

for municipio, sub in df.groupby("municipio"):
    sub_unique = sub.drop_duplicates(subset=["nombre"])
    seleccion = sub_unique.head(3)

    for _, row in seleccion.iterrows():
        rows.append({
            "municipio": municipio,
            "nombre": row["nombre"],
            "grupo": row["grupo"],
            "url_maps": maps_url(row["nombre"], municipio)
        })

restaurantes = pd.DataFrame(rows).sort_values(["municipio", "nombre"])

restaurantes

,municipio,nombre,grupo,url_maps
0,Frontera,Cruz Alta,Bar-Cafeteria,https://www.google.com/maps/search/Cruz%20Alta...
2,Frontera,El Matorral (Auto Bar),Bar-Cafeteria,https://www.google.com/maps/search/El%20Matorr...
1,Frontera,Sabor Criollo,Bar-Cafeteria,https://www.google.com/maps/search/Sabor%20Cri...
5,Valverde,"Disco-Pub ""La Lonja""",Bar-Cafeteria,https://www.google.com/maps/search/Disco-Pub%2...
4,Valverde,Los Reyes,Bar-Cafeteria,https://www.google.com/maps/search/Los%20Reyes...
3,Valverde,Manila,Bar-Cafeteria,https://www.google.com/maps/search/Manila%20Va...

In [5]:
restaurantes.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\el_hierro_ocio\clean_dataset\restaurantes_el_hierro.csv", index=False, encoding="utf-8")

**Alojamientos**

url = https://datos.canarias.es/catalogos/general/dataset/?q=alojamientos+canarias&sort=score+desc%2C+metadata_modified+desc&page=2

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\alojamientos_declarados_a_la_candidatura_canaria.csv")

df_el_hierro = df[df["nom_isla"].str.strip().str.upper() == "EL HIERRO"]

print("Total alojamientos en El hierro:", len(df_el_hierro))

df_el_hierro.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\el_hierro_ocio\dirty_dataset\alojamientos_el_hierro_sucio.csv", index=False)

Total alojamientos en El hierro: 97

In [8]:
import pandas as pd
import urllib.parse


df = pd.read_csv(
    r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\el_hierro_ocio\dirty_dataset\alojamientos_el_hierro_sucio.csv",
    sep=",",
    engine="python",
    on_bad_lines="skip"
)

df = df.rename(columns={
    "nom_municipio": "municipio",
    "etiqueta": "nombre",
    "nom_tipo": "tipo",
    "nom_categor": "categoria"
})

df["municipio"] = df["municipio"].astype(str).str.strip()
df["nombre"] = df["nombre"].astype(str).str.strip()
df["tipo"] = df["tipo"].astype(str).str.strip()
df["categoria"] = df["categoria"].astype(str).str.strip()


df = df[df["municipio"].isin(["Frontera", "Valverde"])]

def maps_url(nombre, municipio):
    q = urllib.parse.quote(f"{nombre} {municipio} El Hierro")
    return f"https://www.google.com/maps/search/{q}"


rows = []

for municipio, sub in df.groupby("municipio"):
    sub = sub.drop_duplicates(subset=["nombre"])

    seleccion = sub.head(3)

    for _, row in seleccion.iterrows():
        rows.append({
            "municipio": municipio,
            "nombre": row["nombre"],
            "tipo": row["tipo"],
            "url_maps": maps_url(row["nombre"], municipio)
        })

alojamientos_limpio = pd.DataFrame(rows).sort_values(["municipio", "nombre"])
alojamientos_limpio

,municipio,nombre,tipo,url_maps
0,Frontera,APARTAMENTOS LA PALMERA,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
2,Frontera,HOTEL BALNEARIO POZO DE LA SALUD,Hotel,https://www.google.com/maps/search/HOTEL%20BAL...
1,Frontera,HOTEL PUNTA GRANDE,Hotel,https://www.google.com/maps/search/HOTEL%20PUN...
4,Valverde,HOTEL BOOMERANG,Hotel,https://www.google.com/maps/search/HOTEL%20BOO...
3,Valverde,PARADOR DE TURISMO DE EL HIERRO,Hotel,https://www.google.com/maps/search/PARADOR%20D...
5,Valverde,PENSION CASAŃAS,Hotel,https://www.google.com/maps/search/PENSION%20C...

In [9]:
alojamientos_limpio.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\el_hierro_ocio\clean_dataset\alojamientos_el_hierro.csv", index=False)