**Restaurantes**

url=https://datos.canarias.es/catalogos/general/dataset/establecimientos-de-restauracion-inscritos-en-el-registro-general-turistico-de-canarias

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\establecimientos-de-restauracion-inscritos-en-el-registro-general-turistico-de-canarias.csv",sep=";")

df_la_gomera = df[df["direccion_isla_nombre"].str.strip().str.lower() == "la gomera"]

df_la_gomera.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_gomera_ocio\dirty_dataset\restauracion_la_gomera_sucio.csv", index=False, sep=";")

print("✔ Archivo generado")
print("Total registros de La Gomera:", len(df_la_gomera))

✔ Archivo generado
Total registros de La Gomera: 359

In [4]:
import pandas as pd
import urllib.parse

df = pd.read_csv(
    r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_gomera_ocio\dirty_dataset\restauracion_la_gomera_sucio.csv",
    sep=";"
)

df = df.rename(columns={
    "direccion_municipio": "municipio",
    "establecimiento_nombre_comercial": "nombre",
    "establecimiento_grupo": "grupo"
})

df["municipio"] = df["municipio"].astype(str).str.strip()
df["nombre"] = df["nombre"].astype(str).str.strip()
df["grupo"] = df["grupo"].astype(str).str.strip()


df = df[df["municipio"] != "_U"]

def maps_url(nombre, municipio):
    q = urllib.parse.quote(f"{nombre} {municipio} La Gomera")
    return f"https://www.google.com/maps/search/{q}"

rows = []

for municipio, sub in df.groupby("municipio"):
    sub_unique = sub.drop_duplicates(subset=["nombre"])
    seleccion = sub_unique.head(2)

    for _, row in seleccion.iterrows():
        rows.append({
            "municipio": municipio,
            "nombre": row["nombre"],
            "grupo": row["grupo"],
            "url_maps": maps_url(row["nombre"], municipio)
        })

restaurantes = pd.DataFrame(rows).sort_values(["municipio", "nombre"])

restaurantes

,municipio,nombre,grupo,url_maps
1,Agulo,Avenida,Bar-Cafeteria,https://www.google.com/maps/search/Avenida%20A...
0,Agulo,El Mantillo,Bar-Cafeteria,https://www.google.com/maps/search/El%20Mantil...
2,Alajero,Bar Restaurante La Chalana,Bar-Cafeteria,https://www.google.com/maps/search/Bar%20Resta...
3,Alajero,La Alegría,Bar-Cafeteria,https://www.google.com/maps/search/La%20Alegr%...
4,Hermigua,Grafiano,Bar-Cafeteria,https://www.google.com/maps/search/Grafiano%20...
5,Hermigua,Piloto,Bar-Cafeteria,https://www.google.com/maps/search/Piloto%20He...
7,San Sebastian De La Gomera,La Candelaria,Bar-Cafeteria,https://www.google.com/maps/search/La%20Candel...
6,San Sebastian De La Gomera,La Pista,Bar-Cafeteria,https://www.google.com/maps/search/La%20Pista%...
8,Valle Gran Rey,Edén Libre,Bar-Cafeteria,https://www.google.com/maps/search/Ed%C3%A9n%2...
9,Valle Gran Rey,La Parada,Bar-Cafeteria,https://www.google.com/maps/search/La%20Parada...
10,Vallehermoso,Los Mocanes,Bar-Cafeteria,https://www.google.com/maps/search/Los%20Mocan...
11,Vallehermoso,Luisa,Bar-Cafeteria,https://www.google.com/maps/search/Luisa%20Val...

In [5]:
restaurantes.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_gomera_ocio\clean_dataset\restaurantes_la_gomera.csv", index=False, encoding="utf-8")

**Alojamientos**

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\alojamientos_declarados_a_la_candidatura_canaria.csv")

df_la_gomera = df[df["nom_isla"].str.strip().str.upper() == "LA GOMERA"]

print("Total alojamientos en La Gomera:", len(df_la_gomera))

df_la_gomera.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_gomera_ocio\dirty_dataset\alojamientos_la_gomera_sucio.csv", index=False)

Total alojamientos en La Gomera: 368

In [7]:
import pandas as pd
import urllib.parse


df = pd.read_csv(
    r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_gomera_ocio\dirty_dataset\alojamientos_la_gomera_sucio.csv",
    sep=",",
    engine="python",
    on_bad_lines="skip"
)

df = df.rename(columns={
    "nom_municipio": "municipio",
    "etiqueta": "nombre",
    "nom_tipo": "tipo",
    "nom_categor": "categoria"
})


df["municipio"] = df["municipio"].astype(str).str.strip()
df["nombre"] = df["nombre"].astype(str).str.strip()
df["tipo"] = df["tipo"].astype(str).str.strip()
df["categoria"] = df["categoria"].astype(str).str.strip()

def maps_url(nombre, municipio):
    q = urllib.parse.quote(f"{nombre} {municipio} La Gomera")
    return f"https://www.google.com/maps/search/{q}"

rows = []

for municipio, sub in df.groupby("municipio"):
    sub = sub.drop_duplicates(subset=["nombre"])

    seleccion = sub.head(2)

    for _, row in seleccion.iterrows():
        rows.append({
            "municipio": municipio,
            "nombre": row["nombre"],
            "tipo": row["tipo"],
            "url_maps": maps_url(row["nombre"], municipio)
        })

alojamientos_limpio = pd.DataFrame(rows).sort_values(["municipio", "nombre"])


alojamientos_limpio

,municipio,nombre,tipo,url_maps
0,Agulo,APARTAMENTOS BAJIP,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
1,Alajeró,APARTAMENTOS CASANOVA I,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
2,Alajeró,APARTAMENTOS TAPAHUGA,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
4,Hermigua,APARTAMENTOS CASA DIVERSA,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
3,Hermigua,APARTAMENTOS LOS TELARES,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
5,San Sebastián de La Gomera,HOTEL JARDIN TECINA,Hotel,https://www.google.com/maps/search/HOTEL%20JAR...
6,San Sebastián de La Gomera,PARADOR DE TURISMO CONDE DE LA GOMERA,Hotel,https://www.google.com/maps/search/PARADOR%20D...
8,Valle Gran Rey,HOTEL CANDELARIA,Hotel,https://www.google.com/maps/search/HOTEL%20CAN...
7,Valle Gran Rey,HOTEL GRAN REY,Hotel,https://www.google.com/maps/search/HOTEL%20GRA...
10,Vallehermoso,HOTEL ARGAYALL,Hotel,https://www.google.com/maps/search/HOTEL%20ARG...
9,Vallehermoso,HOTEL SONIA,Hotel,https://www.google.com/maps/search/HOTEL%20SON...

In [8]:

alojamientos_limpio.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_gomera_ocio\clean_dataset\alojamientos_la_gomera.csv", index=False)